apiVersion: v1
kind: ReplicationController
metadata:
    name: "rcweb"
    
spec:
    replicas: 4
    selector:
        env: dev
        dc: IN
    template:
        metadata:
            name: mypod1
            labels:
                env: dev
                dc: IN
        spec:
            containers:
            - name: "mycon1"
              image: "vimal13/apache-webserver-php"
