apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: "rswp"

spec:
    replicas: 1
    selector:
        matchLabels:
            env: dev
            app: wp
    template:
        metadata:
            name: wppod
            labels:
                env: dev
                app: wp
        spec:
            containers:
            - name: "wpimage"
              image: "wordpress:4.8-apache"
            
